# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26fb5ad76638dda90542376d30b6f566155057d8979c67edbf14c5e570b55673a9bf2f1eb3f3879d61b6a7a7b55bcdb13dce7c4598e7e7114472f9ea022da396

test:
  secret_key_base: 6131054a56286928097701e1755f18f76c14a266c251bbefb27b913764e293de521b28a5cbba874744a20a3e599a81b4e15b114676a1efa225b26dbd80a5d929

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
